// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjTUTCPZZ_CexJZ6UqFZcXuGTR9nkc_1w',
    appId: '1:1062871469674:web:0178c2b3ffcee88cb28413',
    messagingSenderId: '1062871469674',
    projectId: 'safespine-6f2ce',
    authDomain: 'safespine-6f2ce.firebaseapp.com',
    storageBucket: 'safespine-6f2ce.appspot.com',
    measurementId: 'G-KNQWN94LNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3llyaXhfElVPWNAOjYHidbXUS_IdTInw',
    appId: '1:1062871469674:android:abf61a26048eac1cb28413',
    messagingSenderId: '1062871469674',
    projectId: 'safespine-6f2ce',
    storageBucket: 'safespine-6f2ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCmx7T0I_PpztEBsV3UGH5wtyDmB6rZc',
    appId: '1:1062871469674:ios:99a10e1c2aea9234b28413',
    messagingSenderId: '1062871469674',
    projectId: 'safespine-6f2ce',
    storageBucket: 'safespine-6f2ce.appspot.com',
    iosClientId: '1062871469674-sc61hu0gu5hjs9dssfrqdfff54g3dmhu.apps.googleusercontent.com',
    iosBundleId: 'com.ortholink.safespine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVCmx7T0I_PpztEBsV3UGH5wtyDmB6rZc',
    appId: '1:1062871469674:ios:99a10e1c2aea9234b28413',
    messagingSenderId: '1062871469674',
    projectId: 'safespine-6f2ce',
    storageBucket: 'safespine-6f2ce.appspot.com',
    iosClientId: '1062871469674-sc61hu0gu5hjs9dssfrqdfff54g3dmhu.apps.googleusercontent.com',
    iosBundleId: 'com.ortholink.safespine',
  );
}
